name: Deploy to Production Server

on:
    push:
        branches:
            - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js 19
      uses: actions/setup-node@v2
      with:
        node-version: '19'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key and known hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > deploy_key
        chmod 600 deploy_key
        ssh-keyscan -H 165.227.228.82 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        rsync -r --delete-after --quiet --chown=www-data:www-data -e "ssh -i deploy_key" ${{ github.workspace }}/ ${{ secrets.SERVER }}
    - name: Set up Python Environment and Restart Service
      run: |
        ssh -i deploy_key ${{ secrets.SERVER_IP }} '$HOME/bin/deploy.sh'

        
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        SERVER: ${{ secrets.SERVER }}
        SERVER_IP: ${{secrets.SERVER_IP}}
    

